CUDA_VISIBLE_DEVICES=0 python $1 &
CUDA_VISIBLE_DEVICES=1 python $1 &
CUDA_VISIBLE_DEVICES=2 python $1 &
CUDA_VISIBLE_DEVICES=3 python $1 &
CUDA_VISIBLE_DEVICES=4 python $1 &
CUDA_VISIBLE_DEVICES=5 python $1 &
CUDA_VISIBLE_DEVICES=6 python $1 &
CUDA_VISIBLE_DEVICES=7 python $1 &
wait
